//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ordShop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ordShopEntities : DbContext
    {
        public ordShopEntities()
            : base("name=ordShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ord_clients> ord_clients { get; set; }
        public virtual DbSet<ord_products> ord_products { get; set; }
        public virtual DbSet<ord_purchaseOrders> ord_purchaseOrders { get; set; }
        public virtual DbSet<ord_purchaseOrdersBody> ord_purchaseOrdersBody { get; set; }
    }
}
